In [2]:
!pip install pandas

Collecting pandas
  Downloading pandas-1.4.2-cp38-cp38-win_amd64.whl (10.6 MB)
Collecting numpy>=1.18.5
  Downloading numpy-1.22.3-cp38-cp38-win_amd64.whl (14.7 MB)
Requirement already satisfied: python-dateutil>=2.8.1 in d:\software\python\envs\r-tutorial\lib\site-packages (from pandas) (2.8.2)
Collecting pytz>=2020.1
  Downloading pytz-2022.1-py2.py3-none-any.whl (503 kB)
Requirement already satisfied: six>=1.5 in d:\software\python\envs\r-tutorial\lib\site-packages (from python-dateutil>=2.8.1->pandas) (1.16.0)
Installing collected packages: pytz, numpy, pandas
Successfully installed numpy-1.22.3 pandas-1.4.2 pytz-2022.1

In [3]:
import pandas as pd

In [22]:
df = pd.read_csv ('crop_production.csv')
df

,State_Name,District_Name,Crop_Year,Season,Crop,Area,Production
0,Andaman and Nicobar Islands,NICOBARS,2000,Kharif,Arecanut,1254.0,2000.0
1,Andaman and Nicobar Islands,NICOBARS,2000,Kharif,Other Kharif pulses,2.0,1.0
2,Andaman and Nicobar Islands,NICOBARS,2000,Kharif,Rice,102.0,321.0
3,Andaman and Nicobar Islands,NICOBARS,2000,Whole Year,Banana,176.0,641.0
4,Andaman and Nicobar Islands,NICOBARS,2000,Whole Year,Cashewnut,720.0,165.0
...,...,...,...,...,...,...,...
246086,West Bengal,PURULIA,2014,Summer,Rice,306.0,801.0
246087,West Bengal,PURULIA,2014,Summer,Sesamum,627.0,463.0
246088,West Bengal,PURULIA,2014,Whole Year,Sugarcane,324.0,16250.0
246089,West Bengal,PURULIA,2014,Winter,Rice,279151.0,597899.0
246090,West Bengal,PURULIA,2014,Winter,Sesamum,175.0,88.0

In [23]:
print(df.Crop.unique())

['Arecanut' 'Other Kharif pulses' 'Rice' 'Banana' 'Cashewnut' 'Coconut '
 'Dry ginger' 'Sugarcane' 'Sweet potato' 'Tapioca' 'Black pepper'
 'Dry chillies' 'other oilseeds' 'Turmeric' 'Maize' 'Moong(Green Gram)'
 'Urad' 'Arhar/Tur' 'Groundnut' 'Sunflower' 'Bajra' 'Castor seed'
 'Cotton(lint)' 'Horse-gram' 'Jowar' 'Korra' 'Ragi' 'Tobacco' 'Gram'
 'Wheat' 'Masoor' 'Sesamum' 'Linseed' 'Safflower' 'Onion'
 'other misc. pulses' 'Samai' 'Small millets' 'Coriander' 'Potato'
 'Other  Rabi pulses' 'Soyabean' 'Beans & Mutter(Vegetable)' 'Bhindi'
 'Brinjal' 'Citrus Fruit' 'Cucumber' 'Grapes' 'Mango' 'Orange'
 'other fibres' 'Other Fresh Fruits' 'Other Vegetables' 'Papaya'
 'Pome Fruit' 'Tomato' 'Rapeseed &Mustard' 'Mesta' 'Cowpea(Lobia)' 'Lemon'
 'Pome Granet' 'Sapota' 'Cabbage' 'Peas  (vegetable)' 'Niger seed'
 'Bottle Gourd' 'Sannhamp' 'Varagu' 'Garlic' 'Ginger' 'Oilseeds total'
 'Pulses total' 'Jute' 'Peas & beans (Pulses)' 'Blackgram' 'Paddy'
 'Pineapple' 'Barley' 'Khesari' 'Guar seed' 'Moth'
 'Other Cereals & Millets' 'Cond-spcs other' 'Turnip' 'Carrot' 'Redish'
 'Arcanut (Processed)' 'Atcanut (Raw)' 'Cashewnut Processed'
 'Cashewnut Raw' 'Cardamom' 'Rubber' 'Bitter Gourd' 'Drum Stick'
 'Jack Fruit' 'Snak Guard' 'Pump Kin' 'Tea' 'Coffee' 'Cauliflower'
 'Other Citrus Fruit' 'Water Melon' 'Total foodgrain' 'Kapas' 'Colocosia'
 'Lentil' 'Bean' 'Jobster' 'Perilla' 'Rajmash Kholar' 'Ricebean (nagadal)'
 'Ash Gourd' 'Beet Root' 'Lab-Lab' 'Ribed Guard' 'Yam' 'Apple' 'Peach'
 'Pear' 'Plums' 'Litchi' 'Ber' 'Other Dry Fruit' 'Jute & mesta']

In [24]:
TN=df[["State_Name"] == "Tamil Nadu", "crop"].unique()

KeyError: (False, 'crop')

In [20]:
df.Crop.unique(df.State_Name='Tamil Nadu')

SyntaxError: expression cannot contain assignment, perhaps you meant "=="? (Temp/ipykernel_21328/3608539371.py, line 1)

In [25]:
df.set_index('State_Name')

,District_Name,Crop_Year,Season,Crop,Area,Production
State_Name,,,,,,
Andaman and Nicobar Islands,NICOBARS,2000,Kharif,Arecanut,1254.0,2000.0
Andaman and Nicobar Islands,NICOBARS,2000,Kharif,Other Kharif pulses,2.0,1.0
Andaman and Nicobar Islands,NICOBARS,2000,Kharif,Rice,102.0,321.0
Andaman and Nicobar Islands,NICOBARS,2000,Whole Year,Banana,176.0,641.0
Andaman and Nicobar Islands,NICOBARS,2000,Whole Year,Cashewnut,720.0,165.0
...,...,...,...,...,...,...
West Bengal,PURULIA,2014,Summer,Rice,306.0,801.0
West Bengal,PURULIA,2014,Summer,Sesamum,627.0,463.0
West Bengal,PURULIA,2014,Whole Year,Sugarcane,324.0,16250.0
West Bengal,PURULIA,2014,Winter,Rice,279151.0,597899.0
West Bengal,PURULIA,2014,Winter,Sesamum,175.0,88.0

In [26]:
print(df.State_Name.unique())

['Andaman and Nicobar Islands' 'Andhra Pradesh' 'Arunachal Pradesh'
 'Assam' 'Bihar' 'Chandigarh' 'Chhattisgarh' 'Dadra and Nagar Haveli'
 'Goa' 'Gujarat' 'Haryana' 'Himachal Pradesh' 'Jammu and Kashmir '
 'Jharkhand' 'Karnataka' 'Kerala' 'Madhya Pradesh' 'Maharashtra' 'Manipur'
 'Meghalaya' 'Mizoram' 'Nagaland' 'Odisha' 'Puducherry' 'Punjab'
 'Rajasthan' 'Sikkim' 'Tamil Nadu' 'Telangana ' 'Tripura' 'Uttar Pradesh'
 'Uttarakhand' 'West Bengal']

In [27]:
df.set_index('States',inplace=True)

KeyError: "None of ['States'] are in the columns"

In [1]:
!pip install seaborn

Collecting seaborn
  Downloading seaborn-0.11.2-py3-none-any.whl (292 kB)
Requirement already satisfied: numpy>=1.15 in d:\software\python\envs\r-tutorial\lib\site-packages (from seaborn) (1.22.3)
Collecting matplotlib>=2.2
  Downloading matplotlib-3.5.1-cp38-cp38-win_amd64.whl (7.2 MB)
Collecting scipy>=1.0
  Downloading scipy-1.8.0-cp38-cp38-win_amd64.whl (36.9 MB)
Requirement already satisfied: pandas>=0.23 in d:\software\python\envs\r-tutorial\lib\site-packages (from seaborn) (1.4.2)
Collecting kiwisolver>=1.0.1
  Downloading kiwisolver-1.4.2-cp38-cp38-win_amd64.whl (55 kB)
Requirement already satisfied: python-dateutil>=2.7 in d:\software\python\envs\r-tutorial\lib\site-packages (from matplotlib>=2.2->seaborn) (2.8.2)
Requirement already satisfied: pillow>=6.2.0 in d:\software\python\envs\r-tutorial\lib\site-packages (from matplotlib>=2.2->seaborn) (9.0.1)
Collecting cycler>=0.10
  Downloading cycler-0.11.0-py3-none-any.whl (6.4 kB)
Requirement already satisfied: packaging>=20.0 in d:\software\python\envs\r-tutorial\lib\site-packages (from matplotlib>=2.2->seaborn) (21.0)
Requirement already satisfied: pyparsing>=2.2.1 in d:\software\python\envs\r-tutorial\lib\site-packages (from matplotlib>=2.2->seaborn) (2.4.7)
Collecting fonttools>=4.22.0
  Downloading fonttools-4.31.2-py3-none-any.whl (899 kB)
Requirement already satisfied: pytz>=2020.1 in d:\software\python\envs\r-tutorial\lib\site-packages (from pandas>=0.23->seaborn) (2022.1)
Requirement already satisfied: six>=1.5 in d:\software\python\envs\r-tutorial\lib\site-packages (from python-dateutil>=2.7->matplotlib>=2.2->seaborn) (1.16.0)
Installing collected packages: kiwisolver, fonttools, cycler, scipy, matplotlib, seaborn
Successfully installed cycler-0.11.0 fonttools-4.31.2 kiwisolver-1.4.2 matplotlib-3.5.1 scipy-1.8.0 seaborn-0.11.2